# Generated by Django 5.2.7 on 2025-11-03 07:16

import HRMIS.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameextension', HRMIS.models.NameField(choices=[('JR', 'Jr'), ('SR', 'Sr')], max_length=50)),
                ('middlename', HRMIS.models.NameField(max_length=20)),
                ('employeenumber', models.CharField(max_length=10)),
                ('dateofbirth', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=30)),
                ('placeofbirth', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
