# Generated by Django 5.2.7 on 2025-11-04 06:41

import HRMIS.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameextension', HRMIS.models.NameField(choices=[('JR', 'Jr'), ('SR', 'Sr')], max_length=50)),
                ('middlename', HRMIS.models.NameField(max_length=20)),
                ('employeenumber', models.CharField(max_length=10)),
                ('dateofbirth', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=30)),
                ('placeofbirth', models.CharField(max_length=50)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('bloodtype', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('gsisno', models.CharField(max_length=15)),
                ('pagibigno', models.CharField(max_length=15)),
                ('philhealthno', models.CharField(max_length=15)),
                ('sssno', models.CharField(max_length=15)),
                ('tinno', models.CharField(max_length=15)),
                ('permhouseblockno', models.IntegerField(blank=True, null=True)),
                ('permstreetno', models.CharField(max_length=100)),
                ('permsubdivisionvillage', models.CharField(max_length=20)),
                ('permbarangay', models.CharField(max_length=30)),
                ('permcitymunicipality', models.CharField(max_length=30)),
                ('permprovince', models.CharField(max_length=30)),
                ('permzipcode', models.IntegerField(blank=True, null=True)),
                ('temphouseblockno', models.IntegerField(blank=True, null=True)),
                ('tempstreetno', models.CharField(max_length=100)),
                ('tempsubdivisionvillage', models.CharField(max_length=20)),
                ('tempbarangay', models.CharField(max_length=30)),
                ('tempcitymunicipality', models.CharField(max_length=30)),
                ('tempprovince', models.CharField(max_length=30)),
                ('tempzipcode', models.IntegerField(blank=True, null=True)),
                ('telephonenumber', models.CharField(max_length=15)),
                ('mobilenumber', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50)),
                ('civilstatus', models.CharField(choices=[('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('SINGLE', 'Single')], max_length=50)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
